version: 0.2

env:
  variables:
    CACHE_CONTROL: "84600"
    S3_BUCKET: "rothstein-codedeploy-lightsail-bucket"
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-verisons:
      nodejs: 12
    commands:
      - echo Installing NPM dependencies
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Building application
      - npm run build
artifacts:
    files:
      - '**/*'
    base-directory: 'dist*'
    discard-paths: yes